In [1]:
import numpy as np

import os

In [2]:
dir='/home/milad/Desktop/python/DL/Mini_project/db/glove.6B'
embeddings_index={}
with open(f'{dir}/glove.6B.100d.txt',encoding='utf-8') as f:
  lines=f.readlines()
  for line in lines:
    values=line.split()
    word=values[0]
    embed=values[1:]
    weights=np.asarray(embed,dtype='float32')
    embeddings_index[word]=weights

len(embeddings_index.keys())

400000

In [3]:
from sklearn.metrics.pairwise import cosine_similarity

def similarity(u,v):
  return np.squeeze(cosine_similarity(u.reshape(1,-1),v.reshape(1,-1)))

In [4]:
embeddings_index['father']

array([ 0.64706 , -0.068067,  0.15468 , -0.17408 , -0.29134 ,  0.76999 ,
       -0.3192  , -0.25663 , -0.25082 , -0.036737, -0.25509 ,  0.29636 ,
        0.5776  ,  0.49641 ,  0.19167 , -0.83888 ,  0.58482 , -0.38717 ,
       -0.71591 ,  0.9519  , -0.37966 , -0.1131  ,  0.47154 ,  0.20921 ,
        0.38197 ,  0.067582, -0.92879 , -1.1237  ,  0.84831 ,  0.68744 ,
       -0.15472 ,  0.92714 ,  0.53371 , -0.037392, -0.856   ,  0.19056 ,
       -0.014594,  0.15186 ,  0.53514 , -0.20306 , -0.35164 ,  0.33152 ,
        1.1306  , -0.72787 , -0.19724 ,  0.031659, -0.24041 , -0.057617,
        0.60473 , -0.49233 , -0.24405 , -0.3184  ,  0.96156 ,  1.0895  ,
        0.21534 , -2.0542  , -1.0615  ,  0.052439,  0.57958 ,  0.2748  ,
        0.91587 ,  0.85195 ,  0.36113 , -0.31901 ,  0.7784  , -0.36865 ,
        0.64387 ,  0.33104 , -0.27181 ,  0.58524 , -0.15143 ,  0.11121 ,
        0.2126  , -0.60345 ,  0.16148 ,  0.32952 , -0.1354  , -0.30629 ,
       -0.89143 ,  0.091912,  0.49753 ,  0.55932 , 

In [5]:
father = embeddings_index['father']
mother = embeddings_index['mother']
tehran = embeddings_index['tehran']
paris = embeddings_index['paris']
france = embeddings_index['france']
iran = embeddings_index['iran']

In [6]:
similarity(father,mother)

array(0.8656661, dtype=float32)

In [7]:
similarity(tehran,paris)

array(0.45368147, dtype=float32)

In [8]:
similarity(france,iran)

array(0.46655208, dtype=float32)

In [9]:
similarity(france - paris,iran - tehran)

array(0.6854124, dtype=float32)

In [10]:
similarity(france - paris,tehran - iran)

array(-0.6854124, dtype=float32)

In [11]:
def complete_analogy(word_a,word_b,word_c,embeddings_index):
  word_a,word_b,word_c = word_a.lower(),word_b.lower(),word_c.lower()

  e_a,e_b,e_c = embeddings_index[word_a],embeddings_index[word_b],embeddings_index[word_c]

  words = embeddings_index.keys()
  max_cosine_sim=float('-inf')
  best_word=None

  for w in words:
    if w in [word_a,word_b,word_c]:
      continue

    cosine_sim = similarity(e_b - e_a, embeddings_index[w] - e_c)

    if cosine_sim > max_cosine_sim:
      max_cosine_sim = cosine_sim
      best_word = w


  return best_word


In [12]:
complete_analogy('china','chinese','iran',embeddings_index)

'iranian'

In [13]:
embeddings_index['friends']

array([ 4.5009e-01,  1.6062e-01,  1.1566e-01, -5.3179e-01, -7.2739e-02,
        8.7249e-01, -2.7337e-01,  3.9109e-02, -1.1082e-01, -6.7418e-01,
       -5.8561e-03, -2.7491e-01,  4.4526e-01,  2.7253e-01, -1.4088e-01,
       -6.3118e-01,  3.3957e-01, -2.3398e-01, -8.2852e-01,  8.2585e-01,
       -1.0884e-01,  4.0506e-01,  4.1654e-02, -3.8506e-01,  1.8556e-01,
        1.0295e-02, -3.7407e-01, -2.1638e-01,  8.0129e-01,  1.9284e-01,
        3.8775e-01,  8.0588e-01,  5.3309e-01,  1.4667e-01,  1.8727e-01,
        5.4205e-01,  3.6400e-01,  1.1027e-01,  4.1861e-01, -2.7823e-01,
       -4.4245e-01,  1.4767e-01,  2.5920e-01, -3.3971e-01, -3.1072e-01,
       -2.6700e-01, -6.7109e-01,  5.3856e-01,  6.7125e-01, -5.1252e-01,
       -1.2794e-01, -4.7893e-01,  1.8934e-01,  7.5955e-01,  1.8978e-01,
       -1.8906e+00, -5.5521e-02, -1.2690e-01,  6.3579e-01,  5.6385e-01,
       -7.5377e-02,  1.4552e+00, -1.7026e-03, -3.5715e-01,  4.9432e-01,
       -1.4183e-01,  6.4131e-01,  5.4293e-01,  6.6209e-01, -1.44

In [14]:
def complete_analogy2(word_a,word_b,word_c,embeddings_index,limit=5):
  word_a,word_b,word_c = word_a.lower(),word_b.lower(),word_c.lower()

  e_a,e_b,e_c = embeddings_index[word_a],embeddings_index[word_b],embeddings_index[word_c]

  words = embeddings_index.keys()
  max_cosine_sim=float('-inf')
  best_word={}

  for w in words:
    #if len(best_word.keys()) >=limit:
      #break
    if w in [word_a,word_b,word_c]:
      continue

    cosine_sim = similarity(e_b - e_a, embeddings_index[w] - e_c)

    if cosine_sim > max_cosine_sim:
      max_cosine_sim = cosine_sim
      best_word[w] = cosine_sim


  return sorted(best_word.items(),key=lambda x:x[1],reverse=True)[:limit]

In [15]:
complete_analogy2('china','chinese','iran',embeddings_index)

[('iranian', array(0.796303, dtype=float32)),
 ('turkish', array(0.6328089, dtype=float32)),
 ('greek', array(0.60495967, dtype=float32)),
 ('iraqi', array(0.57764673, dtype=float32)),
 ('russian', array(0.5115686, dtype=float32))]

In [16]:
embeddings_index['iranian']

array([ 0.74124  ,  0.11045  ,  0.56782  , -0.065495 ,  0.33851  ,
       -0.39176  , -0.80394  , -0.60198  ,  0.24519  ,  1.7734   ,
        0.13633  , -0.27694  ,  1.3715   ,  0.15865  , -0.62266  ,
        0.56927  , -0.40329  , -0.76107  , -0.78117  , -0.12852  ,
        0.019008 , -0.014354 ,  0.30912  , -0.10408  , -0.80433  ,
       -0.069777 , -0.44361  ,  0.24099  ,  1.1195   ,  0.96748  ,
       -0.24555  , -0.10438  , -0.6079   , -0.328    ,  0.045156 ,
       -0.14803  ,  0.12835  ,  0.29054  , -0.23727  ,  0.25611  ,
       -1.1144   ,  0.10325  ,  0.15149  ,  0.26347  ,  0.86872  ,
       -1.3337   ,  0.14206  , -0.17506  , -0.16883  ,  0.47317  ,
        0.44096  ,  0.46944  ,  0.99419  ,  1.0463   , -0.65101  ,
       -0.80263  , -0.47383  ,  0.064334 ,  1.4847   ,  0.056562 ,
       -0.1044   , -0.059878 , -0.11622  , -0.74952  ,  0.36067  ,
        0.53188  ,  0.29301  ,  0.15941  , -0.84449  ,  0.37091  ,
        0.76953  , -0.12229  ,  0.54898  , -0.33458  ,  0.0019

In [17]:
embeddings_index['can']

array([-0.71766 ,  0.80871 ,  0.31868 , -0.53589 , -0.31998 ,  0.18929 ,
       -0.23241 ,  0.44233 ,  0.25649 , -0.32093 , -0.16951 ,  0.14993 ,
        0.55681 ,  0.33992 ,  0.028335, -0.38295 ,  0.43366 ,  0.73026 ,
       -0.79863 ,  0.2954  ,  0.017078, -0.39545 ,  0.19967 ,  0.081727,
        0.18943 ,  0.095973, -0.033138, -0.69888 ,  0.41562 , -0.67422 ,
       -0.059873,  1.23    , -0.31391 ,  0.15313 ,  0.82508 ,  0.49345 ,
       -0.051686,  0.31035 ,  0.25147 , -0.36228 , -0.14969 , -0.39609 ,
       -0.73853 , -1.0716  , -0.21775 ,  0.23018 ,  0.078188, -0.48584 ,
       -0.082414, -1.0405  ,  0.44389 , -0.2964  ,  0.036505,  1.2115  ,
        0.50287 , -2.2662  , -0.073575,  0.010925,  1.7266  ,  0.63332 ,
       -0.23215 ,  1.2603  , -0.43585 , -0.082693,  1.1903  ,  0.34009 ,
        0.59365 ,  0.20098 ,  0.1016  , -1.1757  , -0.1187  , -0.59569 ,
        0.34427 , -0.48687 ,  0.34953 , -0.44521 , -0.13131 , -0.19316 ,
       -0.55304 ,  0.075953,  0.6893  , -0.26706 , 

In [18]:
embeddings_index['sara'],embeddings_index["'s"],embeddings_index['car']

(array([-0.23295 , -0.56497 , -0.19626 ,  0.19975 , -0.032222, -0.38232 ,
        -0.029728,  0.73616 ,  0.58323 , -0.71157 ,  0.39422 , -0.30442 ,
        -0.24572 ,  0.17488 , -0.18663 , -0.11994 ,  0.84987 ,  0.10857 ,
        -0.68445 ,  1.0525  ,  0.13365 ,  0.064299,  0.83515 ,  1.1555  ,
         0.1825  ,  0.69425 ,  0.6002  , -0.94532 , -0.31604 ,  0.58163 ,
        -0.29775 ,  0.16136 ,  0.40526 , -0.34496 , -0.29017 , -0.11178 ,
         0.63977 ,  0.48543 ,  0.37657 , -0.31775 ,  0.13887 , -0.27289 ,
         0.17381 ,  0.1177  , -0.27849 , -0.20353 , -0.30238 ,  0.16277 ,
         0.30644 ,  0.37662 , -0.16699 ,  0.32401 ,  0.24019 ,  0.49195 ,
         0.17648 , -0.77485 , -0.71654 ,  0.29765 , -0.4008  , -0.43771 ,
         0.6624  ,  0.26549 ,  0.31074 , -0.13082 , -0.22054 , -0.37281 ,
         0.74097 ,  0.81706 ,  0.033166,  0.062954, -0.18385 ,  0.48533 ,
        -0.64557 ,  0.036766,  0.61796 ,  0.50265 , -0.38559 , -0.15885 ,
         0.057809, -0.025447, -0.24995