In [2]:
import numpy as np

In [3]:
dir='/home/milad/Desktop/python/DL/Mini_project/db/glove.6B'
embeddings_index={}
words_to_index={}
index_to_words={}
with open(f'{dir}/glove.6B.100d.txt',encoding='utf-8') as f:
  lines=f.readlines()
  words =set()
  for line in lines:
    values=line.split()
    word=values[0]
    embed=values[1:]
    weights=np.asarray(embed,dtype='float32')
    embeddings_index[word]=weights
    words.add(word)

  i = 1
  for w in sorted(words):
    words_to_index[w]=i
    index_to_words[i]=w
    i+=1


len(embeddings_index.keys())


400000

In [4]:
word='sara'
words_to_index[word]

318272

In [5]:
index_to_words[318272]

'sara'

In [6]:
def senetences_to_indices(X,word_to_index,max_len):
  m=X.shape[0]
  X_indices=np.zeros((m,max_len))

  for i in range(m):
    sentence_words=X[i].lower().split()
    for j,w in enumerate(sentence_words):
      X_indices[i,j]=words_to_index[w]

  return X_indices

In [7]:
X=np.array(['funny','lets go party','food is ready for you'])
X_indices=senetences_to_indices(X,words_to_index,max_len=5)
print(X)
print(X_indices)
# [[1234,0,0,0,0],[654,3242,123,0,0],[121,123,23,454,123]]

['funny' 'lets go party' 'food is ready for you']
[[155345.      0.      0.      0.      0.]
 [220930. 163237. 278093.      0.      0.]
 [151204. 192973. 302254. 151349. 394475.]]
